name: Auto Create Pull Request

on:
  push:
    branches:
      - '*'
      - '!develop'
      - '!quality'
      - '!staging'

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-requests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Garante que todas as branches sejam carregadas

      - name: Extract branch name
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "Branch identificada: $BRANCH_NAME"

      - name: Fetch branches
        run: |
          git fetch origin develop quality staging
          git branch -a

      - name: Ensure branches are up to date
        run: |
          git checkout develop && git pull origin develop
          git checkout quality && git pull origin quality
          git checkout staging && git pull origin staging

      - name: Create PR to develop
        run: |
          gh pr create --base develop --head ${{ env.BRANCH_NAME }} --title "${{ env.BRANCH_NAME }} - Auto PR → develop" --body "Este PR foi gerado automaticamente."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR to quality
        run: |
          gh pr create --base quality --head ${{ env.BRANCH_NAME }} --title "${{ env.BRANCH_NAME }} - Auto PR → quality" --body "Este PR foi gerado automaticamente."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR to staging
        run: |
          gh pr create --base staging --head ${{ env.BRANCH_NAME }} --title "${{ env.BRANCH_NAME }} - Auto PR → staging" --body "Este PR foi gerado automaticamente."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
